# Generated by Django 3.1.6 on 2021-06-02 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('locale_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('plugin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('version', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Qgis_version',
            fields=[
                ('qgis_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ui_theme',
            fields=[
                ('ui_theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('telemetry_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('protocol', models.CharField(max_length=45)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.location')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('interface_id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.language')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.locale')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.os')),
                ('qgis_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.qgis_version')),
                ('ui_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.ui_theme')),
            ],
        ),
        migrations.CreateModel(
            name='Added_layer',
            fields=[
                ('added_layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=45)),
                ('extension', models.CharField(max_length=10)),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.telemetry')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.interface')),
                ('plugin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.plugin')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.provider')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.server')),
                ('telemetry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.telemetry')),
            ],
        ),
    ]
